### ISSUE TITLE
Collapse/Hide at different breakpoints?

### ISSUE THREAD

**Issue by bhellman1** [jxnblk/grid-styled#101]
Can grid-styled support collapsing/hidding an element (Box) at different breakpoints? I need this along w flex order to build a responsive layout. Thanks

**Comment by jxnblk** [comment]
I put together this library for such things https://github.com/jxnblk/hidden-styled – but don't think this sort of functionality belongs in grid-styled. You can also extend any grid-styled component with styled-components to suite your needs, e.g. `styled(Box)`
