### ISSUE TITLE
The very first line, on very first example is a little confusing

### ISSUE THREAD

**Issue by skube** [jxnblk/grid-styled#104]
I _think_ (though I could be wrong) that `<Flex..>` wrapper on the first example of [Grid Styled](http://jxnblk.com/grid-styled/) is unnecessary. 

```html
<Flex flexWrap='wrap'>
  <Box p={3} width={[ 1, 2/3, 1/2 ]}>
...
</Flex>
```
I can't see that it does anything. 😕

**Comment by jxnblk** [comment]
That's a remnant from when there was content on the right side of the page. I'd accept a PR cleaning that up a bit

**Comment by skube** [comment]
Ok. I'll do that...just wasn't sure if I wasn't understanding something.
