### ISSUE TITLE
Adding gutter feature to Box/Flex component

### ISSUE THREAD

**Issue by jzimmek** [jxnblk/grid-styled#106]
I really enjoy using grid-styled and quickly learned that it is build upon styled-system.

Using Box/Flex as building blocks works 90% for me. But from time to time I want some Box/Flex have a gutter between elements of the same type. Or for direct child elements.

I wrote some responsiveStyle using styled-system:

```
const gutterY = responsiveStyle({
  prop: "gutter",
  cssProperty: "marginTop",
  key: "space"
});

const gutterX = responsiveStyle({
  prop: "gutter",
  cssProperty: "marginLeft",
  key: "space"
});
```

And some companion helper to make those usable in styled-components:

```
export const gutterSelfX = css`
  & + & {
    ${gutterX};
  }
`;

export const gutterSelfY = css`
  & + & {
    ${gutterY};
  }
`;

export const gutterChildrenX = css`
  > * + * {
    ${gutterX};
  }
`;

export const gutterChildrenY = css`
  > * + * {
    ${gutterY};
  }
`;
```

Actual usage looks like this:

Example 1:
```
const MyBoxContainer = styled(Box)`
  ${gutterChildrenY}
`
....
<MyBoxContainer gutterChildrenY={3}>
  <Box>box1</Box>
  <Box>box1</Box>
  <Box>box1</Box>
</MyBoxContainer>
```

Example 2:
```
const MyBox = styled(Box)`
  ${gutterSelfY}
`
....
<div>
  {someArray.map(e => <MyBox gutterSelfY={3}>box</MyBox>)}
</div>
```

I think it is quite a common pattern to have some vertical/horizontal gutter between elements - which can not always be implemented with flexbox.

Would be great to have the "gutterSelf / gutterChildren" responsiveStyle directly as a feature inside grid-styled Box/Flex component.

What do you think?

**Comment by jxnblk** [comment]
Thanks! I think this is very similar to the intent behind [styled-space](https://github.com/jxnblk/grid-styled/tree/master/styled-space), which can be used in conjunction with grid-styled, e.g.

```jsx
<Flex>
  <Space mx={3}>
    <h1>Hello</h1>
    <Box>Beep</Box>
  </Space>
</Flex>
```

Personally I'd rather stick to the same prop names for margin/padding rather than create another abstraction if that makes sense

**Comment by jzimmek** [comment]
Yeah, this is indeed very similar ;-) Great!

I read through the grid-styled/src folder and README but did not found any mention of styled-space and totally overlooked the styled-space folder.

Will try it out, but it looks very promising. You should definitely mention styled-space in the README.

**Comment by karland** [comment]
Because I already added styled-space to the related section in the README.md in this [PR #102](https://github.com/jxnblk/grid-styled/pull/102) I just extended the PR by adding the above example.

**Comment by jzimmek** [comment]
I tried styled-space to implement my "gutter" use case and run into two issues:

1.)
The m* attribute in < Space /> is applied to all child elements. My use case is to have space only between the child elements.

```
<Space>
  <p>1</p>
  <!-- here spacing -->
  <p>2</p>
  <!-- here spacing -->
  <p>3</p>
</Space>
```

This could be fixed by having an additional (negative) margin on the < Space /> itself, but is kinda cumbersome.

2.)
The < Space /> component assumes that the children will be styled-components too. And do not work with non-DOM based child components, like Higher-Order-Components. Those do not always pass through all props (className) to the wrapped component. Adding extra <Box/> tags around the children might be a solution, but this quickly adds up and will have extra impact when being inside < Flex />.

Is there a way to solve 2.) ? 

Both problems could imho be solved by adding the following to the < Box /> component:


```
const gy = responsiveStyle({
  prop: "gy",
  cssProperty: "marginTop",
  key: "space"
});

const gx = responsiveStyle({
  prop: "gx",
  cssProperty: "marginLeft",
  key: "space"
});

...

> * + * {
  ${gx};
  ${gy};
}
```

This would nicely fit into the existing naming scheme:

```
<Box gx={3}>
  <Box>1</Box>
  <Box>2</Box>
  <Box>3</Box>
</Box>
```

Already tried to implement this in a fork but unfortunatly did not get it to work.

Would love to hear your thoughts about this.

**Comment by jxnblk** [comment]
Thanks for the feedback, but I think some of the things suggested are probably more complex than I'd like this API to be. To compensate for extra padding in columns, I'd suggest using negative margins. The components in this library can also be extended/wrapped to achieve the APIs described above
