### ISSUE TITLE
Error when importing Flex

### ISSUE THREAD

**Issue by dannibje** [jxnblk/grid-styled#109]
Getting this error in browser console when trying to import Flex into my project.  

<img width="455" alt="screen shot 2018-05-28 at 15 03 44" src="https://user-images.githubusercontent.com/9742634/40620634-11fc59e0-6289-11e8-8af0-d48e5a9c4487.png">

Line 2 in app.js is 

`import { Flex } from "grid-styled";`

I just cant seem to figure out the problem.

**Comment by corygibbons** [comment]
@dannibje I just had the same problem and managed to resolve it, you may have a similar issue.

For me the project I'm working on is still using webpack v1 which doesn't load JSON by default and requires a loader. `_htmlTags2` comes from the `html-tags` dependency which exports a JSON object which my webpack config didn't know how to handle.

I installed `json-loader` and added it to my webpack config and it's working as expected.

**Comment by jxnblk** [comment]
Closing this since it seems like the above addresses the issue, but please reopen if not
