### ISSUE TITLE
What is the use of theme spacing beyong the fourth item?

### ISSUE THREAD

**Issue by webketje** [jxnblk/grid-styled#110]
From the docs:

> Using a number from 0-4 will reference a step on the spacing scale. Larger numbers are converted to pixel values.

> The default scale is based on an 8px/powers-of-two grid: [ 0, 4, 8, 16, 32, 64, 128, 256, 512 ]

### 2 problems
* In the example the spacings 64,128,256 and 512 cannot be referenced unless directly (e.g. `{512}`, or `"512px"`), so they are no use to grid-styled? I know they can be used by styled-components, but I don't see how they are relevant to grid-styled.
* When I write `<Box mt={4}/>`, I get `<div style="margin-top: 32px;"></div>`. When I write `<Box mt={5}/>` I get `<div style="margin-top: 5px;"></div>`. The component shouldn't act differently with the same prop signature (and why at the 5th item, which is probably less than the amount of spacing values that most teams would define)? 

What I'm getting at is: integer values should either mean 'pixel' or 'spacing scale', not both. And if they mean spacing scale, they should not be arbitrarily capped at the 5th position.

**Comment by corygibbons** [comment]
> What I'm getting at is: integer values should either mean 'pixel' or 'spacing scale', not both.

@webketje In my experience if the integer you supply exists as an index in the space array the value will be pulled from the theme. If not it will function as a px value.

As far as I can tell the documentation there is incorrect.

Here's a CodeSandbox demo showing the first 8 being pulled from the theme and the 9th becoming `9px`:

https://codesandbox.io/s/32xovlvyxm?hidenavigation=1

You likely have an outdated version of `styled-system`, as the `space` array used to look like this:

```js
const space = [ 0, 8, 16, 32, 64 ];
```

Which would explain why `{5}` is turning into `5px`.

**Comment by webketje** [comment]
Hey @corygibbons thanks for chiming in and for the useful info.
I guess this issue changes to "_Correct the documentation on this point_" then.

**Comment by jxnblk** [comment]
> As far as I can tell the documentation there is incorrect.

^^ Can anyone link to the place in the documentation?

**Comment by corygibbons** [comment]
https://github.com/jxnblk/grid-styled#margin-and-padding-props
