### ISSUE TITLE
Extending component, new props passed to tag

### ISSUE THREAD

**Issue by rlopez4** [jxnblk/grid-styled#113]
I am extending the Box component like so:
```javascript
const NavMenuContainer = styled(Box)`
  background: ${props => props.isClosed ? 'white' : 'black' };
  ...
`
```

I am using a new prop isClosed to decide something but it is not blacklisted so I'm getting this error:
```
Warning: React does not recognize the `isClosed` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isclosed` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Clean.div)
    in Clean.div (created by Box)
    in Box (created by Navbar__NavMenuContainer)
    in Navbar__NavMenuContainer (at Navbar.js:77)
    ...
```

This might actually be an issue with styled-system or clean-tag.

**Comment by jxnblk** [comment]
You'll probably want to use the `blacklist` prop to blacklist your own custom prop names: https://github.com/jxnblk/styled-system/tree/master/clean-tag#blacklist-prop

For your particular example, I'd recommend using the `bg` prop instead of using styled-components, e.g.:

```jsx
const NavMenuContainer = ({ open, ...props }) =>
  <Box
    {...props}
    bg={open ? 'black' : 'white'}
  />
```

**Comment by rlopez4** [comment]
Using blacklist works but you would need to extend the existing blacklist with any new props since it won't extend the existing blacklist on Tag.
