### ISSUE TITLE
Add support for emotion

### ISSUE THREAD

**Issue by jxnblk** [jxnblk/grid-styled#116]

**Comment by felipeleusin** [comment]
I'm actually on my way to send a PR to https://github.com/emotion-js/grid-emotion to update to grid-styled 4 but i'll have to learn a little bit of rollup now since grid-styled no longers ships with ./src

If you need any help, I can try to tackle this directly here

**Comment by felipeleusin** [comment]
So, I looked into it and it seems just so troublesome to be doing some sort of roollup magic that it seems simpler to just make a fork and keep it up to date.
The only things I had to change was the import from styled-components to react-emotion and switch from Box.extend to styled(Box).

Would you be ok with something like this?

**Comment by jxnblk** [comment]
Yeah, I was thinking a setup similar to the Babel scripts in Rebass: https://github.com/jxnblk/rebass/blob/master/.babelrc

This library could use system-components, but I think the first step can be along the lines of what you suggested. Would love some help if you wanna take a stab at it
