### ISSUE TITLE
Received a `function` for a string attribute `is`

### ISSUE THREAD

**Issue by zhulduz** [jxnblk/grid-styled#125]
Hi,
After upgrading to `4.3.2` I always catch the warning "Received a `function` for a string attribute `is`"

My code example:
```
const StyledDiv = Flex.extend`
  ...some extra styles
`.withComponent('div')
```

Thanks in advance

**Comment by jxnblk** [comment]
Thanks for reporting this! You shouldn't need the `withComponent` method since Flex renders a `div` by default. If you do want to change the underlying element, can you try using the Flex `is` prop?

**Comment by zhulduz** [comment]
Thanks for the quick response :thumbsup:
It works now, but I couldn't find any info about `is` prop at the docs.

**Comment by jxnblk** [comment]
Awesome! And looks like the `is` props got missed when I updated the docs a while ago, will need to get that back up there 😬  Here are the docs from styled-system, FWIW https://github.com/jxnblk/styled-system/tree/master/system-components#changing-the-underlying-html-element

**Comment by zhulduz** [comment]
Anyway, thank you for your quick help)
