### ISSUE TITLE
Add width and height to <Flex />

### ISSUE THREAD

**Issue by petertait** [jxnblk/grid-styled#13]
Ability to add width and height to <Flex /> would be great. Scenario I've ran into is wanting to make a fullscreen <Flex /> so I can center the children <Box />'s to the viewport.

**Comment by petertait** [comment]
Realisation that this is not an issue and more of a personal request! I will try and find time to open a pull request when I can.

Thanks for this great project btw!

**Comment by jxnblk** [comment]
You can extend styled components for things like that. E.g.

```
const FullScreen = Flex.extend`
  width: 100vw;
  height: 100vh;
`
```

**Comment by peteruithoven** [comment]
I think we understand that we can override the css, but than we lose the ability to easily use values from the theme.
