### ISSUE TITLE
4.3.2 breaking with publish of system-components 3.0.0

### ISSUE THREAD

**Issue by MatthewLarner** [jxnblk/grid-styled#130]
First of all I love this library, thanks for your work.

https://github.com/jxnblk/grid-styled/blob/d9f79883a5f30e77b8384a22c758f9f2b32c8074/package.json#L50

I think `4.3.2` has too loose a dependency declaration for system-components and 3.0.0 is being installed in our projects causing some layout issues as we haven't updated all of our projects to the new prop names yet.

I think publishing a patch `4.3.3` with the following dependency would help.
```
"system-components": ">=2.2.3 <3.0.0"
```

Thoughts?

**Comment by jxnblk** [comment]
Oh, thanks! Yeah, currently the versioning is too loose. Could probably go with `^2.2` - I'll publish a patch

**Comment by jxnblk** [comment]
`4.3.3` should specify the correct version now, but please let me know if you still see issues

**Comment by MatthewLarner** [comment]
Great thanks! All fixed 👍

**Comment by jay-manday** [comment]
thanks dude! this worked for me to
