### ISSUE TITLE
_react2.default.forwardRef is not a function

### ISSUE THREAD

**Issue by niklasravnsborg** [jxnblk/grid-styled#133]
Hi, this might also be a bug in system-components but grid-styled is what I'm using.

I'm trying to use grid-styled in a Gatsby environment. As soon as I `import { Box, Flex } from 'grid-styled'` in one of my components I get the following error:

<img width="1440" alt="screen shot 2018-07-24 at 09 36 49" src="https://user-images.githubusercontent.com/6717303/43124541-c088cc1c-8f27-11e8-8ed1-41b5f3c83a93.png">

Is there something I can do?

**Comment by mimimimichael** [comment]
Same setup here, though i tried to import the emotion version. Same error message.

**Comment by jxnblk** [comment]
`React.forwardRef` was added in [v16.3.0](https://github.com/facebook/react/releases/tag/v16.3.0). If you’re using an older version of React, you can install the previous version of grid-styled

**Comment by niklasravnsborg** [comment]
All right. Seems ^4.0.0 works without any problems :)
