### ISSUE TITLE
Styles doesn't get applied in Internet Explorer 11

### ISSUE THREAD

**Issue by thupi** [jxnblk/grid-styled#136]
I recently tried out this grid system and instantly liked it. However, few hours later i found out that it didn't seam to work in IE11 :-) 

I wasn't able to debug it. No errors but the styles somhow didn't get applied to the elements even though the className was applied to the element. Anyone with similar experiences ? :-)

Is IE11 a supported browser?

**Comment by jxnblk** [comment]
Sounds like this might be an issue with styled-components or emotion, if you want to open an issue on one of those repos
