### ISSUE TITLE
bootstrap xs={12} md={4} like functionality

### ISSUE THREAD

**Issue by dagda1** [jxnblk/grid-styled#14]
If I want a div to take up a 33.333% width in devices that are not mobile and a 100% width in mobile

In bootstrap I would do this:
`<Col xs={12} md={4}>{children}</Col>`

How would I do this in grid-styled?

**Comment by jxnblk** [comment]
It would looks something like this:

```jsx
// For the xs and sm breakpoints:
<Box w={[ 1, 1/3 ]} />

// Or to skip the sm breakpoint:
<Box w={[ 1, null, 1/3 ]} />
```

See https://github.com/jxnblk/styled-system#responsive-styles and please let me know how I can make the docs better or if the above doesn't make sense.

**Comment by jxnblk** [comment]
For xs and sm breakpoints, it'd be something like:

**Comment by zebapy** [comment]
It's much nicer to have `xs/sm/md/lg` props for skipping breakpoints. I'm trying to create this with 

```jsx
const Column = ({ xs = 12, sm, md, lg, ...props }) => {
  const cols = [xs, sm, md, lg].map(x => (x ? x / 12 : null));

  return <Box w={cols} flex="1 1 auto" px={3} {...props} />;
};
```

but it's not working. The default `xs=12` isn't creating a breakpoint class. Any idea? How can I return the fraction but not evaluate it?

**Comment by chibicode** [comment]
The key is to add `flexWrap="wrap"` to the outer `Flex`:

```js
<Flex mx={-2} flexWrap="wrap">
  <Box width={[1, 1 / 3]} px={2}>
    One
  </Box>
  <Box width={[1, 1 / 3]} px={2}>
    Two
  </Box>
  <Box width={[1, 1 / 3]} px={2}>
    Three
  </Box>
</Flex>
```
