### ISSUE TITLE
Breakpoint values assigned to key

### ISSUE THREAD

**Issue by coreybruyere** [jxnblk/grid-styled#140]
Currently I have my breakpoints defined like so:
```
  breakpoints: {
    mobile: '20em',
    tablet: '46.250em',
    desktop: '70em',
    wide: '81.250em',
  }
```
Is there any way for the `<Box>` component to use values assigned to a key?

**Comment by jxnblk** [comment]
Currently with the way styled-system works, `breakpoints` needs to be an array. You can add keys as aliases to the array if you intend to use them outside of grid-styled/styled-system, e.g.:

```js
const breakpoints = [
  '32em',
  '48em'
]
breakpoints.small = breakpoints[0]
breakpoints.medium = breakpoints[1]
```
