### ISSUE TITLE
Support for `flex`, `flex-shrink` and `flex-grow`

### ISSUE THREAD

**Issue by TimonVS** [jxnblk/grid-styled#18]
I sometimes have the need to set the [`flex` property](https://developer.mozilla.org/nl/docs/Web/CSS/flex) of an element. Right now I'd have to extend the `Flex` component using Styled Components or use inline styles (which don't get prefixed).

I was wondering if there is a reason that the `flex` property is not supported right now. If there's no reason than I'll gladly create a PR that implements this feature :).

**Comment by jxnblk** [comment]
It's not in the readme yet, but I just added a `flex` prop in last night – it should work on any of the components. E.g. `<Box flex='1 1 auto' />`

**Comment by TimonVS** [comment]
Ah, right. Thanks :)
