### ISSUE TITLE
Responsive Order

### ISSUE THREAD

**Issue by cschroeter** [jxnblk/grid-styled#24]
First of all - this is an awesome library ! Thanks for all the time you spend on it.

I love the way you handle the responsive sizing.

Is there a way to do similiar things with the Flex order property?

```<Flex order={[1, 1, 0]} />```

**Comment by jxnblk** [comment]
It is possible, and I can see the use case for that. I'd accept a PR for something like this – might make more sense for the styled-system library to export some utilities to handle this

**Comment by tibotiber** [comment]
This would be great, I can see this used at large for all props. For instance, I got here looking for a way to do this for with `justify` and I guess `align` and `wrap` could be getting the same behaviour.

**Comment by TroutZen** [comment]
Looking for similar functionality for other props as well. Trying to figure out how to change the flex direction based on breakpoints.

**Comment by jxnblk** [comment]
I'm planning on adding in support for responsive flex properties for `order`, 'flex-direction`, and `wrap` based on the change here: https://github.com/jxnblk/styled-system/pull/14

**Comment by jxnblk** [comment]
With `2.0.0-8` you can set responsive styles for `order`, `wrap`, `direction`, `align`, and `justify`

E.g.
```jsx
<Box order={[ 2, 1 ]} />
```

```jsx
<Flex
  wrap={[ true, false ]}
  direction={[ 'column', 'row' ]}
  align={[ 'stretch', 'center' ]}
  justify={[ 'space-between', 'center' ]}
/>
```
