### ISSUE TITLE
Access to flex-direction property?

### ISSUE THREAD

**Issue by searleb** [jxnblk/grid-styled#25]
I don't know if I'm missing something in the docs but I can only see a `bool` to switch between `row` and `column` directions.
I took a look at the Flex component and could something like the following be added?
```
const direction = props => props.direction ? `flex-direction:${props.direction};` : null
```
It would conflict with the current `column` prop though.
Thoughts?

Cheers

**Comment by jxnblk** [comment]
I think `direction` probably makes sense as its own prop, perhaps keeping `column` as a shortcut to setting `flex-direction: column`. I'll probably add that in based on the discussion in #24

**Comment by jxnblk** [comment]
With `2.0.0-8` a `direction` prop is now supported, see #24 for an example
