### ISSUE TITLE
typescript definitions

### ISSUE THREAD

**Issue by Arthelon** [jxnblk/grid-styled#26]
Is there anyone currently working on writing typescript definitions for this project? If not, I'll have a go at it myself in a few hours

**Comment by rohmanhm** [comment]
Nice @Arthelon 
PR Welcome

**Comment by jxnblk** [comment]
I'm assuming this would be a separate library?? Closing this for now, but feel free to continue the discussion

**Comment by rohmanhm** [comment]
For now, I just using my own **grid-styled.d.ts** file.

```typescript
declare module 'grid-styled' {
  export const Flex: any
  export const Box: any
  export const Grid: any
}
```

It will be nice if it have official typescript definitions 🙂

**Comment by Arthelon** [comment]
@jxnblk this would either be a new entry in the [definitelytyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repo or included directly in here (index.d.ts)

**Comment by rohmanhm** [comment]
@Arthelon I recommended just put directly to here. So user can get type def quickly without install via `npm i --save-dev @types/grid-styled`

**Comment by HyunSeob** [comment]
Any updates?

**Comment by antonvasin** [comment]
@HyunSeob got sidetracked but will make PR soon

**Comment by JamesTheHacker** [comment]
Really looking forward to this update.
