### ISSUE TITLE
react-native support

### ISSUE THREAD

**Issue by smooJitter** [jxnblk/grid-styled#28]
Does this work with react-native / glamorous

**Comment by jxnblk** [comment]
For glamorous see https://github.com/jxnblk/styled-system

For react native, I'd like to explore support for it but it's certainly not a priority right now since I do zero native app development. I'm guessing using styled-components/primitives might work though

**Comment by lucastobrazil** [comment]
Just curious here - does it still not work on react-native? i installed it but getting some build errors 
`TransformError: Couldn't find preset "env" relative to root directory`. Not sure if i should bother trying to troubleshoot if RN isn't supported anyway. Cheers!
