### ISSUE TITLE
<Box w={1200}> should use max-width

### ISSUE THREAD

**Issue by karland** [jxnblk/grid-styled#31]
`<Box w={1200}>` is resulting in `width: 1200px`, but for responsive displays I think it would be better to have:

```CSS
width: 100%;
max-width: 1200px;
```

**Comment by jxnblk** [comment]
The `width` prop sets width. For max-width you can extend the component:

```
const Container = styled(Box)`
  max-width: 1200px;
`
```

**Comment by karland** [comment]
Thanks for the quick response. I do not quite understand why you use `width`. Say you have a Box that has `w={1200}`, but in a responsive context the display size is say 1920 or only 1024. In the case of 1024, I believe the width should be set to `width: 100%` and you should not use `width: 1200px` because then you have to deal with too wide boxes and overflows.

**Comment by jxnblk** [comment]
You generally shouldn't set fixed pixel widths on elements – even outside of this particular library. The `<Box />` component is mostly meant to be used for fractional widths, e.g. `<Box w={1/2} />` (50%). The ability to set pixel widths is an escape hatch for special cases. The docs don't show any cases where `w={1200}` because it's not really a recommended way of using this library.

**Comment by karland** [comment]
Thanks again for the response. I perfectly agree with all you say. 

>The ability to set pixel widths is an escape hatch for special cases. 

I have opened this issue probably only because I thought the standard use case for the `w`-element would be to confine the outer `<Flex w={1200} m={"auto"}>` on screens that are larger then `1200w`, for instance, to prevent images to become too big. Many websites restrict the width to a maximum width. The boxes within the Flex would then use the percentage width as you say. Of course, it would not be a problem to wrap the `<Flex>` in a `<Container>` with `width:1200`.

**Comment by jxnblk** [comment]
Sorry for the confusion, please let me know if there's anything in particular in the docs that seemed to suggest that. grid-styled is meant to be fairly low-level, but Rebass has more components that wrap up functionality like the `<Container />` component: http://jxnblk.com/rebass/components/Container

**Comment by karland** [comment]
grid-styled is great, so don't be sorry. By the way: I had a look at rebass and I like it too. 

This is from the docs. I am still not sure what the use case is for that in a responsive context.
> // Fixed pixel width
> <Box width={256} />
>
> // CSS value width
> <Box width='40em' />

But anyway, I think we can really close the issue. Best.

**Comment by jxnblk** [comment]
Thanks! FWIW I do occasionally find setting fixed widths useful for small elements like icons and images, and em units can be very useful for RWD
