### ISSUE TITLE
Feature request: make 'display' a responsive attribute

### ISSUE THREAD

**Issue by smashercosmo** [jxnblk/grid-styled#35]
Reason: if I need to change layout direction to provide responsiveness, most of the time I prefer not to switch between 'row' and 'column' values of flex-direction, but just switch flex layout on and off altogether by changing display property. I prefer this because flex-direction column is pretty buggy and because in most cases for mobile layout you need just a normal elements stack without any fancy flex behaviour. So my proposal is to make a display property responsive, so that you could 
<Flex display={['block', 'flex']}>. What do you think?

**Comment by jxnblk** [comment]
The method you described is how I tend to handle flexbox breaking down, but I'm not sure the Flex component is the right place to do that. I think it'd make sense in the Box component or perhaps a more generic Display component though

**Comment by smashercosmo** [comment]
Yeah, just wanted to point this out) Feel free to close.

**Comment by jxnblk** [comment]
As a follow up, you could achieve this with an extended component and using styled-system's [`responsiveStyle`](https://github.com/jxnblk/styled-system#responsivestyle) utility.

```jsx
import { Flex } from 'grid-styled'
import { responsiveStyle } from 'styled-system'

const display = responsiveStyle({
  prop: 'display'
})
const Display = Flex.extend([], display)
```
