### ISSUE TITLE
Responsiveness doesn't change on parent resize

### ISSUE THREAD

**Issue by webchaz** [jxnblk/grid-styled#37]
I have my Flex grid setup with a parent container.  If I resize the browser, the breakpoints seem to trigger as expected, however if I update the parent containers width to simulate a mobile preview, it doesn't seem to adjust.  Any idea if something else needs to occurs?

**Comment by jxnblk** [comment]
Media queries only detect changes in the viewport. What you're describing is often referred to as "container queries," which don't actually exist in CSS
