### ISSUE TITLE
Feature Request: "hide" property

### ISSUE THREAD

**Issue by j** [jxnblk/grid-styled#39]
It would be cool if I can hide within the grid system perhaps?

```javascript
<Box hide={[false, true]} ...> // hides on everything but smallest bp
<Box hide={[true, false]} ...> // hides only on smallest bp
<Box hide={[true, false, true]} ...> // only shows on second bp
```

**Comment by jacobpdq** [comment]
Maybe this helps you

```
// Example
import styled from 'styled-components'
import { Box } from 'grid-styled'
import breakpoint from 'styled-components-breakpoint';
import theme from '../../../theme'

const breakpoints = {
	xs: theme.breakpoints[0]*16,
	sm: theme.breakpoints[1]*16,
	md: theme.breakpoints[2]*16,
	lg: theme.breakpoints[3]*16,
	xl: theme.breakpoints[4]*16,
}

const StyledBox = styled(Box)`

	  ${breakpoint('xl', breakpoints)`
	    ${  props => props.w === undefined ? 0 : props.w[0] === 0 ? 'display:none;' : 'display:initial' }
	  `}
  	  ${breakpoint('sm', breakpoints)`
	    ${  props => props.w === undefined ? 0 : props.w[1] === 0 ? 'display:none;' : 'display:initial' }
	  `}
  	  ${breakpoint('md', breakpoints)`
	    ${  props => props.w === undefined ? 0 : props.w[2] === 0 ? 'display:none;' : 'display:initial' }
	  `}
  	  ${breakpoint('lg', breakpoints)`
	    ${  props => props.w === undefined ? 0 : props.w[3] === 0 ? 'display:none;' : 'display:initial' }
	  `}
	  ${breakpoint('xl', breakpoints)`
	    ${  props => props.w === undefined ? 0 : props.w[4] === 0 ? 'display:none;' : 'display:initial' }
	  `}

`
export default StyledBox

```

**Comment by gregwym** [comment]
While I believe @jacobpdq's solution works, show and hide element responsively is a quite common use case. Most layout/grid framework has `.hidden`/`.show` classes for this purpose. It should be built into https://github.com/jxnblk/styled-system.

**Comment by jxnblk** [comment]
I made https://github.com/jxnblk/hidden-styled for things like this. Showing/hiding content responsively is sort of an anti-pattern in my opinion, and I wouldn't want to include it in this library – but I'd accept PRs for making hidden-styled more compatible with styled-system

**Comment by MiguelMadero** [comment]
> Showing/hiding content responsively is sort of an anti-pattern in my opinion

I'm curious about why do you think this is the case and if you have any resources to learn more about this.

**Comment by jxnblk** [comment]
Just to follow up, I'd consider it an anti-pattern because following a mobile-first responsive approach means that whatever works for mobile, works for desktop. Showing and hiding content based on viewport widths means that the experience can dramatically change for different users, if that makes sense

**Comment by MiguelMadero** [comment]
> if that makes sense

The explanation makes sense. I don't agree, but I understand the rationale. Thanks for clarifying.
