### ISSUE TITLE
Box and Grid give warning with server side rendering

### ISSUE THREAD

**Issue by zentuit** [jxnblk/grid-styled#41]
#If you use Box or Grid in a SSR app (for example - using next.js), you'll see a warning similar to this:

> Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) -in1kw1-1 glNHox sc-htpNat iSNGhk sc-bdV
 (server) -in1kw1-1 glNHox sc-kkGfuU kGURps sc-hMq

The [babel-plugin-styled-components](https://github.com/styled-components/babel-plugin-styled-components) plugin fixes this by generating the displayName and componentId at compile time. That lets the server and client share the same generated class name.

I tried to add the plugin to this project, however Box and Grid don't use TaggedTemplateLiterals which is necessary for the babel plugin to generate the correct code. I've never seen how Box and Grid call `styled` before so I don't know how to go about updating things to get the correct code generated by babel.

For reference, with a component defined like so:
```
const Label = styled.label``
```
in the file `src/components/Label/index.js`, the babel plugin will generate:
```
var Label = _styledComponents2.default.label.withConfig({
  displayName: 'Label__Label',
  componentId: 'bteeh0-0'
})(['']);
```

**Comment by MathiasVI** [comment]
Hey guys, 

Any idea on this? I'm running into a similar issue where classes are different between server side and client side rendering. 

Thanks!

**Comment by zentuit** [comment]
@MathiasVI -- I ended up redoing them locally with tagged template literals. If you want I can share them with you.

**Comment by jxnblk** [comment]
I don't think this is an issue anymore with styled-components v3, but feel free to reopen if you still see warnings
