### ISSUE TITLE
Add prop align-self to Box?

### ISSUE THREAD

**Issue by karland** [jxnblk/grid-styled#43]
It is nice that `<Flex/>` allows the alignment of its children, however, currently children are not able to break out of their alignment (if I have not overlooked it). Would you consider to add `align-self` or a shorthand such as `align` as a prop to the `<Box/>` at least in order to match the flexbox specification also in this respect?

```JSX
<Flex align="center" direction="column">
    <Box>
        Aligned centered
    </Box>
    <Box align-self="flex-end">
        Expose align-self as a prop
    </Box>
    <Box align="flex-end">
        Expose align as a shorthand for align-self as a prop
    </Box>
</Flex>
```

**Comment by karland** [comment]
I know extensions are possible, but I still think to have this as standard prop for `<Box />` in `grid-styled` is nicer...

```JSX
import styled from "styled-components"
import { Box } from "rebass"

const ExtendedBox = styled(Box).attrs({
  align: props => props.align
})`
  align-self: ${props => props.align};
`

export default ExtendedBox
```

**Comment by jxnblk** [comment]
Added in 4.1.0
