### ISSUE TITLE
ThemeProvider ignored

### ISSUE THREAD

**Issue by aboutlo** [jxnblk/grid-styled#49]
Very cool lib, kudoz!

I'm trying to override the default `breakpoints` and `spaces` but the theme object is empty.

I have configured the theme provider like that:

```
<ThemeProvider theme={theme}>
        <div className="App">
          <Header />
          <main>
            <Container>
              <MyFirstPage />
            </Container>
          </main>
          <Footer />
        </div>
      </ThemeProvider>
```

theme:

```
const theme = {
  space: [ 0, 8, 16, 24, 32 ], // pixels
  breakpoints: [ 32, 64, 75], //em => 320px, 1024px, 1200px
}
export default theme
```

Then in `Footer` I'm using 

```
 <Flex wrap>
          <Box px={2} py={1} width={[1,1,1/5]}>
            <Heading level="5" negative>Bla bla</Heading>
            <Paragraph negative>
              bla bla
            </Paragraph>
          </Box>
</Flex>
```

The theme object in `Flex` or `Box` components is empty rather than in my Heading or Paragraph components I can see it. 
Should I do something different to propagate the `theme`?

**Comment by ipedro** [comment]
Did you find any fix @aboutlo ?

We're having the same issue on our project.

**Comment by aboutlo** [comment]
@ipedro Unfortunately, I didn't work on it lately.

**Comment by ipedro** [comment]
For future reference, our theme breakpoints were ignored because it's an Emotion project and our grid elements were being wrongly imported from `'grid-styled'` instead of the `'grid-emotion'` alias.
