### ISSUE TITLE
SRR Support.

### ISSUE THREAD

**Issue by yasserhennawi** [jxnblk/grid-styled#50]
Functionality breaks when SSR is involved, probably back then styled-component hadn't supported SSR yet, but now that it does, hopefully grid-styled do as well.

**Comment by jxnblk** [comment]
AFAIK this library should work fine with styled-components' SSR implementation. Do you have any code for reference where this doesn't work?

**Comment by ciro-maciel** [comment]
Hi, great project! I'm fascinated by simplicity and features.

Thank you @jxnblk!

@yasserhennawi, there is a reason, as he inherited from styled-components, we have been able to use the SSR resources https://www.styled-components.com/docs/advanced#server-side-rendering.

My code looks like this:

```
import express from 'express';
import compression from 'compression';
import fs from 'fs';

import React from 'react';
import { renderToString } from 'react-dom/server';
import { ServerStyleSheet } from 'styled-components';
import { StaticRouter } from 'react-router'
import Helmet from 'react-helmet';

import Main from './main';


let app = express();

app.set("x-powered-by", false);
app.use(compression());

app.use('/assets', express.static(__dirname + '/../public/assets'));
const manifestJs = fs.readFileSync(__dirname + '/../public/assets/js/manifest.js', 'utf8');


app.get('*', function(req, res) {

	const context = {};

	const sheet = new ServerStyleSheet()
	const renderHtml = renderToString(sheet.collectStyles(
		<StaticRouter location={req.url} context={context}>
			<Main />
		</StaticRouter>
	));
	const helmet = Helmet.renderStatic();
	const styled = sheet.getStyleTags()

	const html = `
		<!doctype html>
		<html ${helmet.htmlAttributes.toString()}>
			<head>
				<meta charset="UTF-8">
				${helmet.title.toString()}
				${helmet.meta.toString()}
				${helmet.link.toString()}
				<style>${styled}</style>
				<link rel="icon" type="image/png" href="/assets/img/favicon.png">
				<link rel="manifest" href="/manifest.json">
				<script type="text/javascript" charset="utf-8">${manifestJs}</script>				
			</head>
			<body ${helmet.bodyAttributes.toString()}>
				<div id="container">${renderHtml}</div>
				<script type="text/javascript" src="/assets/js/main.js" charset="utf-8"></script>
			</body>
		</html>
	`;	

	// context.url will contain the URL to redirect to if a <Redirect> was used
	if (context.url) {
		res.writeHead(302, {
			Location: context.url
		})
		res.end()
	} else {
		res.write(html)
		res.end()
	} 

});

app.listen(8080, () => console.log('Listening on http://localhost:8080'));
```

**Comment by MathiasVI** [comment]
Hey guys, 

I'm running into some issues with SSR. Sometimes the classes on the server side rendering are different than the client side rendering. It's a really inconsistent issue but it does mostly happen on Box or Flex elements. I checked and my SSR setup is the same as the one described above and the styled components docs. Any thoughts?

Thanks!

**Comment by juliocanares** [comment]
@MathiasVI did you solve it?

**Comment by yasserhennawi** [comment]
@juliocanares  Sadly for me, as the issue was in the work and due to time pressure, we had to switch over to hedron, tho I personally recommended this to them, SSR is everything to us :/

**Comment by juliocanares** [comment]
@yasserhennawi  thank you I am moving too

**Comment by jxnblk** [comment]
Since this library uses styled-components, you'll need to follow their directions for SSR (which admittedly is a lot more painful that other CSS-in-JS libraries) https://www.styled-components.com/docs/advanced#server-side-rendering
