### ISSUE TITLE
Special Character isn't being interpreted as a valid character

### ISSUE THREAD

**Issue by adamellsworth** [jxnblk/grid-styled#52]
https://github.com/jxnblk/grid-styled/blob/6e8433265717d3d0f25707f71b1600ba2e7fc0aa/src/Golden.js#L4

__Transpiled output:__
```js
Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.B = exports.A = exports.gb = exports.ga = exports.Ï = undefined;

// ...

var Ï = exports.Ï = (1 + Math.sqrt(5)) / 2;
var ga = exports.ga = Ï - 1;
var gb = exports.gb = 1 - ga;
```

Throwing the following Error:
```
Golden.js:6 Uncaught SyntaxError: Invalid or unexpected token
   ...
```

---

I found this by way of rebass#v1.0.4 (using `"grid-styled": "^2.0.0-10",`).

**Comment by jxnblk** [comment]
It should work if you set `<meta charset='utf-8'>` but that's not a good reason to keep it in this library

**Comment by jxnblk** [comment]
The unicode character is removed in v3 – let me know if you're still having issues
