### ISSUE TITLE
Creating a generic Container with grid-styled

### ISSUE THREAD

**Issue by babycourageous** [jxnblk/grid-styled#54]
Hi there

My apologies if this has been addressed and I just missed it but I would like to create either a component or styled component that can act as a Container for the main section of the site. Rather than create a generic styled component with arbitrary padding/margin, I would like to take advantage of grid-styled padding and margin shorthands so it is homogenous with the other grids. I'm trying to avoid having to manually put `px` props everywhere the Container is used. Is this possible?

thanks!

**Comment by jxnblk** [comment]
I'll likely bring one into this library at some point, but see this for reference: https://github.com/jxnblk/grid-styled/blob/page-grid/src/Container.js

**Comment by jxnblk** [comment]
Also see this approach https://github.com/jxnblk/grid-styled#max-width-container
