### ISSUE TITLE
Any examples with fixed side sidebar and rest for the other box ?

### ISSUE THREAD

**Issue by kavink** [jxnblk/grid-styled#59]
I am trying to create a very simple 2 box layout . 1 for the sidebar and other for content body.

As I am new to flex, I tried various permutations from the examples but am unable to do get the same feel.

or maybe an example of implementing this : https://philipwalton.github.io/solved-by-flexbox/demos/holy-grail/

btw: loved the demo page, pretty impressive. !!

**Comment by gausie** [comment]
I'm doing this currently with
```
<Flex>
  <Box width={200}>Side</Box>
  <Box width={1/1}>Main</Box>
</Flex>
```

**Comment by skube** [comment]
@kavink I'm new to this too but [here's an example](https://codesandbox.io/s/5y3964452l?hidenavigation=1) of that holy-grail

Essentially same as @gausie above,

```jsx
    <Box my={2} p={2}>
      Top
    </Box>

    <Flex my={2} flexWrap="wrap">
      <Box w={[1, 100]} mb={[2, 0]} p={2}>
        Navigation
      </Box>
      <Box flex="1" w={[1, 1 / 3]} p={2} mb={[2, 0]} mx={[0, 2]}>
          ...
      </Box>
      <Box w={[1, 100]} p="2">
        Ads
      </Box>
    </Flex>
```

**Comment by jxnblk** [comment]
I think the examples above have addressed the issue, but feel free to reopen if not
