### ISSUE TITLE
True grid

### ISSUE THREAD

**Issue by stevemao** [jxnblk/grid-styled#61]
The current `Grid` component is using `display: 'inline-block'`. Is there any chance to use `display: grid | inline-grid | subgrid;`?

The browser support now is very positive
https://caniuse.com/#feat=css-grid

**Comment by jxnblk** [comment]
For now I'm planning on keeping grid-styled based on flexbox, but may update [react-css-grid](https://github.com/jxnblk/react-css-grid) to do a little more based on the CSS grid layout spec

**Comment by selrond** [comment]
@jxnblk would appreciate this as well, what's your plan with `react-css-grid` currently?
