### ISSUE TITLE
Problem with two instances of styled-components

### ISSUE THREAD

**Issue by lcsrinaldi** [jxnblk/grid-styled#64]
Is there a reason to not use styled-components as peer dependency? 

https://github.com/styled-components/styled-components/issues/1032

If I have installed a different version from yours my application breaks.

**Comment by jxnblk** [comment]
I've loosened the version in the package.json, please let me know if you're still having issues
https://github.com/jxnblk/grid-styled/blob/master/package.json#L45

**Comment by lcsrinaldi** [comment]
Thanks @jxnblk, I'll test this out.

**Comment by smbecker** [comment]
In our app, this update caused `grid-styled` to reference 3.x while we were still using 2.4, which obviously caused issues.
