### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by bringking** [jxnblk/grid-styled#65]
@jxnblk Looks like the activity on this repo is kind of stalled. We use this library heavily at Weedmaps. We would be happy to contribute and are going to open up some PRs soon. Are you still actively working on this?

**Comment by juliocanares** [comment]
@bringking seems like he is not.

We wanna help too

ping @jxnblk

**Comment by bringking** [comment]
@jxnblk We use this in production and like the library a lot. I know running open source is hard, but we want to help! We don't want to have to fork... Let me know how we can help get some of these PR's merged

**Comment by vittorio** [comment]
+1

 ping @jxnblk

**Comment by bringking** [comment]
@jxnblk :( I will have to fork to get some of these issues fixed, thanks for your work!

**Comment by vittorio** [comment]
@bringking please share the link for your fork

**Comment by bringking** [comment]
https://github.com/GhostGroup/grid-styled @vittorio @juliocanares forked here and will accept the open PRs and release under `@ghostgroup/grid-styled` shortly
