### ISSUE TITLE
My react component won't render because the φ is coming up as an illegal character 

### ISSUE THREAD

**Issue by showcasefloyd** [jxnblk/grid-styled#68]
Using this plugin with our react project. It appears to fail when after we run WebPack and I try to run the react components inside of our production environment because of the "φ" phi character. The browser reports an illegal character and then it will break. 

I see that inside of webpack it's using this character is there any way to stop it from doing this?

**Comment by timurista** [comment]
this repo appears to be abandoned by the original owner, but @showcasefloyd we are actively working on this version and have fixed the issuer here: https://github.com/ghostgroup/grid-styled with commit https://github.com/GhostGroup/grid-styled/commit/e68eb91c51a9e46a73536f57dc9c84035ba584d3. 👍

**Comment by GazzaHazza** [comment]
@timurista  - is your fork of this repo being actively worked on?

**Comment by timurista** [comment]
@GazzaHazza yes, we opened it last week have at least 2 developers on it.

**Comment by GazzaHazza** [comment]
@timurista - Awesome and thank you!! Stupid question, how do i install your `grid-styled` instead of this one?

**Comment by timurista** [comment]
`npm i @ghostgroup/grid-styled` check out this repo for more details https://github.com/ghostgroup/grid-styled.

**Comment by GazzaHazza** [comment]
Awesome thanks!

**Comment by showcasefloyd** [comment]
Thanks @timurista . I'll pull the project down from the from the update repo. I appreciate it.

**Comment by jxnblk** [comment]
@showcasefloyd sounds like you might need `<meta charset='utf-8'>` in your document head, but I'll probably remove the unicode character since it can cause issues

**Comment by showcasefloyd** [comment]
@jxnblk I actually tried that first, but it didn't fixed the issue for me. Maybe it has something to do with how Tomcat works, but it didn't fix the issue for me.

**Comment by jxnblk** [comment]
I'll likely remove the unicode character, but that will mean a breaking/major change, which I'd like to include with a few other changes

**Comment by jxnblk** [comment]
Should be fixed in v3
