### ISSUE TITLE
For Padding, if 0-4 reference a step on the scale, how do you set padding === 0?

### ISSUE THREAD

**Issue by bhellman1** [jxnblk/grid-styled#77]
I tried setting my Box padding to 0 but learned that's not possible like so:

          <Box
            p={0}
          >

How do you set a box padding to 0? thanks

**Comment by jxnblk** [comment]
I'd recommend keeping `0` as the first value in your scale, (`[ 0, 4, 8, 16, ...etc ]`) otherwise you can pass a string value: `<Box p='0' />`
