### ISSUE TITLE
Changelog or release notes

### ISSUE THREAD

**Issue by emilbaekdahl** [jxnblk/grid-styled#79]
I really miss either a changelog file or notes for the different releases. E.g. when I upgraded from v2 to v3, it took me way to long to figure out that I just needed to use the `flexDirection` prop.

**Comment by jxnblk** [comment]
I've just started adding release notes since v4. For changes before that, hopefully the commit messages are clear enough to go off of

**Comment by emilbaekdahl** [comment]
Great. Thank you!
