### ISSUE TITLE
Module not found: Can't resolve 'grid-styled'

### ISSUE THREAD

**Issue by joshikeerti** [jxnblk/grid-styled#8]
I just installed the grid-styled component and when I try importing it in my component, I get a module not found error.

Below are my dependencies from package.json

 "dependencies": {
    "grid-styled": "^2.0.0-0",
    "immutable": "^3.8.1",
    "react": "^15.5.4",
    "react-dom": "^15.5.4",
    "react-router": "^4.1.1",
    "react-router-dom": "^4.1.1",
    "redux": "^3.6.0",
    "redux-saga": "^0.15.3",
    "reselect": "^3.0.1",
    "styled-components": "^2.0.1"
  },

**Comment by jxnblk** [comment]
Sorry, I published a version with a missing `main` field in the package. It should be fixed in v `2.0.0-1`
