### ISSUE TITLE
Warning: React does not recognize the `flexWrap` prop on a DOM element. 

### ISSUE THREAD

**Issue by karland** [jxnblk/grid-styled#85]
I am using:

```JSON
    "grid-styled": "^3.2.0",
    "react": "16.2.0",
    "styled-components": "^3.1.6"
```

```JSX
<Flex flexWrap="wrap">
```

produces the following React warning in the console:

"Warning: React does not recognize the `flexWrap` prop on a DOM element. "

The DOM element looks like

```HTML
<div class="sc-bwzfXH hbZeap" flexwrap="wrap">
```

The other Flex props produce similar warnings...

Thanks a lot.

**Comment by jxnblk** [comment]
Can you tell me what version of grid-styled you're using, and if you have styled-system or clean-tag packages installed, those versions as well?

**Comment by mkrds** [comment]
I'm getting same type of errors e.g:

"Warning: React does not recognize the `flexWrap` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `flexwrap` instead. If you accidentally passed it from a parent component, remove it from the DOM element."

And I'm using same stuff without any other styling packages:

    "grid-styled": "^3.2.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-scripts": "1.1.1",
    "styled-components": "^3.1.6",

**Comment by jonathaningram** [comment]
@jxnblk I made a repro:

1. Check out https://github.com/govau/cloud.gov.au/tree/grid-styled-bug
2. `cd www/ui`
3. `yarn`
4. `yarn start`

Check out the console error on the loaded page:

![image](https://user-images.githubusercontent.com/626664/36364150-6db5817a-1596-11e8-9300-ae97b96e8212.png)

Fingers crossed those steps are all you need to reproduce!

**Comment by karland** [comment]
> Can you tell me what version of grid-styled you're using, and if you have styled-system or clean-tag packages installed, those versions as well?

I have not installed `styled-system` or `clean-tag` explicitely. I am relying on yarn installing the dependencies.

My feeling for the warning is that `tag` is applied when declaring [`<Box />` ](https://github.com/jxnblk/grid-styled/blob/0669847c071d8068e882ce5dc955c455c9cbf140/src/Box.js#L13) but not when declaring the extending properties to [`<Flex />`](https://github.com/jxnblk/grid-styled/blob/0669847c071d8068e882ce5dc955c455c9cbf140/src/Flex.js#L9).

**Comment by jxnblk** [comment]
Hmm, sounds like it could be a yarn issue then. Can you try `rm -rf node_modules && npm i` to see if that makes any difference?

**Comment by rlopez4** [comment]
I've run into the same issue with npm

**Comment by jonathaningram** [comment]
I've just `rm -rf node_modules && yarn` on my repro above and it has the same issue. Incidentally: it resulted in a snapshot test being slightly different so you were partly correct that something was different. But, the issue in this ticket still happens...

**Comment by rlopez4** [comment]
I ran into this issue with `minHeight`. I checked the `Clean.div` element that is created and both `minHeight` and `flexWrap` were missing from the blacklist that `Clean.div` uses to prevent from certain props from being passed to the dom element. The blacklist is generated from the list of propTypes provided by styled-system.

Temp Fix: run `npm i clean-tag` to make sure the latest version of clean-tag is installed which should generate a more complete blacklist

**Comment by karland** [comment]
As PRed by @rlopez4 the warnings disappear, when I force yarn to use `"clean-tag": "1.0.3"`, 

For the time being, just add to package.json:

```JSON
  "resolutions": {
    "clean-tag": "1.0.3"
  }
```

From my point of view this issues can be closed. Thank you @jxnblk for the fix and your awesome libraries!

**Comment by vzaidman** [comment]
same happens with `"grid-styled": "^3.2.1"` `"clean-tag": "1.0.4"` ?

**Comment by wayspurrchen** [comment]
This is still an issue, unfortunately. I'm getting a consistent error with `clean-tag@1.0.3`:

Peeking through some of the code it almost looks like `clean-tag` is trying to blacklist every prop that is actually specified by styled-components, but that may be a valid use case. I'm not familiar enough with the code enough to say. In any case, I am getting this error:

![screen shot 2018-06-14 at 2 42 51 pm](https://user-images.githubusercontent.com/1059075/41434459-6da3d4a2-6fe1-11e8-8ef5-66d7dd2de2b7.png)

**Comment by karolisgrinkevicius** [comment]
I still get the same error but the most interesting part this error occurs only on IE and v11 particularly.
