### ISSUE TITLE
Do styled-components@3.1.0 and grid-styled@3.0.0 work together?

### ISSUE THREAD

**Issue by leushkin** [jxnblk/grid-styled#86]
After updating to those versions, entire layout has broken down. But styled-components@2.1.2 (for example) and grid-styled^3.0.0 work well. And old styled-components work well with new grid-styled.

I would like to update, but together they do not work

**Comment by jxnblk** [comment]
These two versions *should* work together. Feel free to reopen this issue if you are still seeing problems
