### ISSUE TITLE
Styles from styled-components get injected at top of <head> instead of bottom

### ISSUE THREAD

**Issue by davin-english** [jxnblk/grid-styled#89]
I noticed this when attempting to use margin features.

If a `<Box>` within my `<Flex>` is using a style that proceeds where the styled-components styles are injected, you end up with none of the overridden styled-components styles working.

For example, I applied `mb={'7px'}` to all of my `<Box>` elements: `<a className={'btn btn-primary'} mb={'7px'}></a>`.

The problem lies here; the styled-component style is overridden by Bootstrap:
![image](https://user-images.githubusercontent.com/1658390/36550707-ec7e2a00-17c3-11e8-8311-376bec88a3f3.png)

Because of where the styled-component style is injected:
![image](https://user-images.githubusercontent.com/1658390/36550886-5da6e500-17c4-11e8-95c7-8f65991d00e0.png)
If you notice, the blue-highlighted style is the styled-component style, but the Bootstrap link comes after it.

Is there any way to make the styled-components injection come last in the `<head>`?

**Comment by jxnblk** [comment]
This seems to be an issue with the styled-components library, I'd follow up on that project since this one doesn't have any way to control how styled-components works

**Comment by jxnblk** [comment]
Also, I would *not* recommend using css libraries like Bootstrap with css-in-js libraries as you'll be running into issues like this one a lot
