### ISSUE TITLE
Help with breakpoints? 

### ISSUE THREAD

**Issue by appsolutegeek** [jxnblk/grid-styled#91]
Hi,

I was happy to find that a breakpoint can be skipped by passing null like so

`[<Box w={[ 1, null, 1/3 ]} />]`

Although, I am confused what breakpoints exists. I checked the other project and it seems set to em 

Does anyone have a good list in px? 

I was hoping to have something like bootstrap I. E. Xs, sm, md, lg etc

**Comment by appsolutegeek** [comment]
I was speaking going to use this project

https://github.com/jxnblk/hidden-styled

And I notice it has the breakpoint names.

**Comment by jxnblk** [comment]
You can customize breakpoints using a ThemeProvider as described here https://github.com/jxnblk/grid-styled/blob/master/README.md#theming

Please let me know if that helps

**Comment by appsolutegeek** [comment]
Hi, yes, thank you, that is helpful BUT are we forced to do this with EM ? Does it support PX ? I was hoping to support the same media breakpoints as bootstrap

**Comment by jxnblk** [comment]
You can use any valid css unit when defined as a string. Numbers are converted to px
