### ISSUE TITLE
Warning: React does not recognize the `alignItems` and `justifyContent` prop on a DOM element.

### ISSUE THREAD

**Issue by vzaidman** [jxnblk/grid-styled#92]
related to #85 

im using `grid-styled 3.2.1`

the problem is here: (the same is true for `alignItems`)
![image](https://user-images.githubusercontent.com/5188459/36669338-343243b8-1afd-11e8-9070-97c2d73e059a.png)

**Comment by jxnblk** [comment]
It looks like you have an older version of styled-system installed. Can you try updating that to the latest?
